relation:
  followers: "followers"
  following: "following"
per_page: 10
default_number_of_answers: 4
number_word: 5
time_lesson: 20
condition_filters:
  - "learned"
  - "not_learned"
  - "all"
default_email: "noreply@fels.com"
